import { Creator, Project, CollabRequest, Flare } from "@/types";

export const MOCK_CREATORS: Creator[] = [
  {
    id: "1",
    name: "Aria Chen",
    handle: "aria.creates",
    avatar: "https://api.dicebear.com/8.x/lorelei/svg?seed=aria&backgroundColor=6c5ce7",
    role: "UI/UX Designer & Motion Artist",
    bio: "Crafting digital experiences that blur the line between art and interface. Obsessed with micro-interactions and dark aesthetics.",
    skills: ["UI Design", "Motion", "Figma", "After Effects", "Framer"],
    followers: 24800,
    following: 412,
    projects: 38,
    verified: true,
    online: true,
    coverGradient: "linear-gradient(135deg, #6c5ce7 0%, #a29bfe 50%, #00d2ff 100%)",
    location: "San Francisco, CA",
    joinedYear: 2022,
    socialLinks: { twitter: "ariacreates", github: "aria-chen", dribbble: "aria" },
  },
  {
    id: "2",
    name: "Zane Okafor",
    handle: "zanecode",
    avatar: "https://api.dicebear.com/8.x/lorelei/svg?seed=zane&backgroundColor=00cec9",
    role: "Full-Stack Engineer & OSS Contributor",
    bio: "Building tomorrow's web today. TypeScript evangelist, performance geek, and open-source maximalist.",
    skills: ["TypeScript", "Rust", "WebGL", "Next.js", "Kubernetes"],
    followers: 18300,
    following: 287,
    projects: 52,
    verified: true,
    online: false,
    coverGradient: "linear-gradient(135deg, #00cec9 0%, #0984e3 100%)",
    location: "Berlin, Germany",
    joinedYear: 2021,
    socialLinks: { github: "zanecode", twitter: "zanecode", linkedin: "zaneokafor" },
  },
  {
    id: "3",
    name: "Luna Voss",
    handle: "lunavisuals",
    avatar: "https://api.dicebear.com/8.x/lorelei/svg?seed=luna&backgroundColor=fd79a8",
    role: "3D Artist & Creative Director",
    bio: "I make things look impossible. Blender wizard, art director, and aesthetics philosopher.",
    skills: ["Blender", "Cinema4D", "Houdini", "Substance", "Midjourney"],
    followers: 41200,
    following: 156,
    projects: 24,
    verified: true,
    online: true,
    coverGradient: "linear-gradient(135deg, #fd79a8 0%, #e17055 50%, #fdcb6e 100%)",
    location: "Tokyo, Japan",
    joinedYear: 2020,
    socialLinks: { twitter: "lunavisuals", dribbble: "luna", instagram: "lunavisuals" } as Creator["socialLinks"],
  },
  {
    id: "4",
    name: "Kira Nakamura",
    handle: "kira.dev",
    avatar: "https://api.dicebear.com/8.x/lorelei/svg?seed=kira&backgroundColor=fdcb6e",
    role: "AI Engineer & Creative Technologist",
    bio: "Making AI human. I build interfaces that think, generative systems that feel, and tools that inspire.",
    skills: ["Python", "PyTorch", "React", "Stable Diffusion", "LLMs"],
    followers: 33600,
    following: 520,
    projects: 19,
    verified: false,
    online: true,
    coverGradient: "linear-gradient(135deg, #fdcb6e 0%, #e17055 100%)",
    location: "New York, NY",
    joinedYear: 2023,
    socialLinks: { github: "kiradev", twitter: "kiradev" },
  },
  {
    id: "5",
    name: "Eli Ramos",
    handle: "eli.motion",
    avatar: "https://api.dicebear.com/8.x/lorelei/svg?seed=eli&backgroundColor=a29bfe",
    role: "Creative Developer & WebGL Artist",
    bio: "Where code meets canvas. Building immersive web experiences with Three.js and GLSL shaders.",
    skills: ["Three.js", "GLSL", "WebGL", "React", "GSAP"],
    followers: 15700,
    following: 301,
    projects: 31,
    verified: true,
    online: false,
    coverGradient: "linear-gradient(135deg, #a29bfe 0%, #6c5ce7 50%, #fd79a8 100%)",
    location: "Barcelona, Spain",
    joinedYear: 2022,
    socialLinks: { github: "elimotion", twitter: "elimotion" },
  },
  {
    id: "6",
    name: "Mia Sterling",
    handle: "mia.brands",
    avatar: "https://api.dicebear.com/8.x/lorelei/svg?seed=mia&backgroundColor=00d2ff",
    role: "Brand Strategist & Visual Identity Designer",
    bio: "I don't design logos. I build identities. Helping startups find their visual voice since 2019.",
    skills: ["Brand Identity", "Typography", "Illustrator", "Strategy", "Figma"],
    followers: 29100,
    following: 198,
    projects: 45,
    verified: true,
    online: true,
    coverGradient: "linear-gradient(135deg, #00d2ff 0%, #0984e3 100%)",
    location: "London, UK",
    joinedYear: 2019,
    socialLinks: { dribbble: "miabrands", twitter: "miabrands", linkedin: "miasterling" },
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "p1",
    title: "Nebula OS — Conceptual UI",
    description: "A futuristic operating system UI concept with AI-driven workspaces, spatial computing elements, and fluid motion design.",
    thumbnail: "",
    tags: ["UI Design", "Motion", "Concept", "Dark Mode"],
    likes: 2840,
    views: 18300,
    creator: { id: "1", name: "Aria Chen", handle: "aria.creates", avatar: "https://api.dicebear.com/8.x/lorelei/svg?seed=aria", verified: true },
    featured: true,
    createdAt: "2024-03-15",
    gradient: "linear-gradient(135deg, #6c5ce7 0%, #a29bfe 50%, #00d2ff 100%)",
  },
  {
    id: "p2",
    title: "Hyperion — WebGL Particle Engine",
    description: "An open-source particle engine built on Three.js with GPU instancing, custom GLSL shaders, and reactive audio.",
    thumbnail: "",
    tags: ["Three.js", "WebGL", "Open Source", "GLSL"],
    likes: 4120,
    views: 29600,
    creator: { id: "5", name: "Eli Ramos", handle: "eli.motion", avatar: "https://api.dicebear.com/8.x/lorelei/svg?seed=eli", verified: true },
    featured: true,
    createdAt: "2024-02-28",
    gradient: "linear-gradient(135deg, #a29bfe 0%, #6c5ce7 50%, #fd79a8 100%)",
  },
  {
    id: "p3",
    title: "DreamForge — AI Image Platform",
    description: "Next-gen AI image generation platform with ControlNet, inpainting, and real-time style transfer at scale.",
    thumbnail: "",
    tags: ["AI", "Python", "React", "Stable Diffusion"],
    likes: 3560,
    views: 22100,
    creator: { id: "4", name: "Kira Nakamura", handle: "kira.dev", avatar: "https://api.dicebear.com/8.x/lorelei/svg?seed=kira", verified: false },
    featured: true,
    createdAt: "2024-01-10",
    gradient: "linear-gradient(135deg, #fdcb6e 0%, #e17055 100%)",
  },
  {
    id: "p4",
    title: "Void — Immersive 3D Experience",
    description: "Award-winning interactive 3D web experience exploring the aesthetics of deep space and solitude.",
    thumbnail: "",
    tags: ["3D Art", "Blender", "WebGL", "Interactive"],
    likes: 6780,
    views: 44200,
    creator: { id: "3", name: "Luna Voss", handle: "lunavisuals", avatar: "https://api.dicebear.com/8.x/lorelei/svg?seed=luna", verified: true },
    featured: true,
    createdAt: "2023-11-20",
    gradient: "linear-gradient(135deg, #fd79a8 0%, #e17055 50%, #fdcb6e 100%)",
  },
  {
    id: "p5",
    title: "Axiom Design System",
    description: "A comprehensive design system for modern SaaS products: 200+ components, dark mode, and full Figma/code parity.",
    thumbnail: "",
    tags: ["Design System", "Figma", "React", "TypeScript"],
    likes: 1920,
    views: 13800,
    creator: { id: "6", name: "Mia Sterling", handle: "mia.brands", avatar: "https://api.dicebear.com/8.x/lorelei/svg?seed=mia", verified: true },
    featured: false,
    createdAt: "2024-04-01",
    gradient: "linear-gradient(135deg, #00d2ff 0%, #0984e3 100%)",
  },
  {
    id: "p6",
    title: "ChronoStack — Dev Productivity CLI",
    description: "A blazing-fast Rust CLI tool that tracks development time, generates changelogs, and syncs with GitHub automatically.",
    thumbnail: "",
    tags: ["Rust", "CLI", "Open Source", "DevTools"],
    likes: 2310,
    views: 16500,
    creator: { id: "2", name: "Zane Okafor", handle: "zanecode", avatar: "https://api.dicebear.com/8.x/lorelei/svg?seed=zane", verified: true },
    featured: false,
    createdAt: "2024-03-22",
    gradient: "linear-gradient(135deg, #00cec9 0%, #0984e3 100%)",
  },
];

export const MOCK_COLLABS: CollabRequest[] = [
  {
    id: "c1",
    title: "Looking for Motion Designer — AI Startup Rebrand",
    description: "Series A startup in the AI space needs a motion designer for our rebrand campaign. 4-week engagement.",
    skills: ["Motion Design", "After Effects", "Brand Identity"],
    type: "paid",
    budget: "$5,000–$8,000",
    creator: { id: "6", name: "Mia Sterling", handle: "mia.brands", avatar: "https://api.dicebear.com/8.x/lorelei/svg?seed=mia", verified: true },
    deadline: "2024-05-30",
    applicants: 7,
  },
  {
    id: "c2",
    title: "Co-build an Open-Source WebGL Framework",
    description: "Building the next layer on top of Three.js for interactive storytelling. Need React and shader experts.",
    skills: ["Three.js", "React", "GLSL", "WebGL"],
    type: "open-source",
    creator: { id: "5", name: "Eli Ramos", handle: "eli.motion", avatar: "https://api.dicebear.com/8.x/lorelei/svg?seed=eli", verified: true },
    applicants: 14,
  },
  {
    id: "c3",
    title: "AI Music Visualizer — Creative Partner Needed",
    description: "Building a real-time AI music visualizer. Need someone with audio engineering + 3D art skills.",
    skills: ["3D Art", "Blender", "Audio", "Python"],
    type: "collab",
    creator: { id: "4", name: "Kira Nakamura", handle: "kira.dev", avatar: "https://api.dicebear.com/8.x/lorelei/svg?seed=kira", verified: false },
    applicants: 3,
  },
];

export const SKILLS_ALL = [
  "UI Design", "UX Research", "Motion Design", "3D Art", "Blender", "Cinema4D",
  "React", "Next.js", "Vue", "TypeScript", "JavaScript", "Rust", "Python",
  "Three.js", "WebGL", "GLSL", "Framer", "Figma", "Brand Identity",
  "AI/ML", "Stable Diffusion", "LLMs", "PyTorch", "Web3", "Solidity",
];

export const MOCK_FEED_POSTS = [
  {
    id: "fp1",
    type: "work_post" as const,
    creator: MOCK_CREATORS[0],
    timestamp: "2h ago",
    title: "Nebula OS — Conceptual UI",
    caption: "A futuristic operating system UI concept with AI-driven workspaces, spatial computing elements, and fluid motion design. Spent the weekend rethinking how we interact with spatial OS elements. Full case study coming soon.",
    mediaUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2564&auto=format&fit=crop",
    tags: ["UI Design", "Motion", "Concept"],
    saves: 342,
    category: "UI Design",
  },
  {
    id: "fp2",
    type: "trending_creator_spotlight" as const,
    creator: MOCK_CREATORS[4],
    timestamp: "5h ago",
    title: "Creator Spotlight: Eli Ramos",
    caption: "Eli's latest WebGL experiments are pushing the boundaries of in-browser real-time rendering. Check out Hyperion, an open-source particle engine built on Three.js.",
    mediaUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=2670&auto=format&fit=crop",
    tags: ["WebGL", "Three.js", "Spotlight"],
    saves: 891,
    category: "Code",
  },
  {
    id: "fp3",
    type: "collab_call" as const,
    creator: MOCK_CREATORS[5],
    timestamp: "12h ago",
    title: "Looking for Motion Designer — AI Startup Rebrand",
    caption: "Series A startup in the AI space needs a motion designer for our rebrand campaign. 4-week engagement. DM with your portfolio if interested.",
    tags: ["Motion Design", "After Effects", "Brand Identity", "Paid Collab"],
    saves: 45,
    category: "Writing",
  },
  {
    id: "fp4",
    type: "work_post" as const,
    creator: MOCK_CREATORS[2],
    timestamp: "1d ago",
    title: "Void — Immersive 3D Experience",
    caption: "Just launched Void. An interactive 3D web experience exploring the aesthetics of deep space and solitude. Built entirely with Blender and custom WebGL shaders.",
    mediaUrl: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?q=80&w=2564&auto=format&fit=crop",
    tags: ["3D Art", "Blender", "WebGL"],
    saves: 1205,
    category: "3D",
  },
  {
    id: "fp5",
    type: "work_post" as const,
    creator: MOCK_CREATORS[3],
    timestamp: "2d ago",
    title: "DreamForge — AI Image Platform",
    caption: "Next-gen AI image generation platform with ControlNet, inpainting, and real-time style transfer at scale. Super excited to finally open the beta waitlist.",
    mediaUrl: "https://images.unsplash.com/photo-1678324424699-4c12513fdf1b?q=80&w=2670&auto=format&fit=crop",
    tags: ["AI", "Stable Diffusion", "Beta"],
    saves: 567,
    category: "UI Design",
  },
  {
    id: "fp6",
    type: "work_post" as const,
    creator: MOCK_CREATORS[4],
    timestamp: "3h ago",
    title: "Short Film Colour Grade — Neon Noir",
    caption: "Finished grading a short film for a local director. Full neon noir treatment — pushed the shadows hard, kept skin tones warm against the city blues. DaVinci Resolve 18 + custom LUTs.",
    mediaUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    tags: ["Video Editing", "Color Grading", "DaVinci Resolve"],
    saves: 218,
    category: "Video",
  },
  {
    id: "fp7",
    type: "trending_creator_spotlight" as const,
    creator: MOCK_CREATORS[1],
    timestamp: "6h ago",
    title: "Creator Spotlight: Beat Architect",
    caption: "This producer built an entire hip-hop instrumental using only field recordings from a street market. No samples, no loops — just raw sound. The result is something genuinely new.",
    mediaUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    tags: ["Music Production", "FL Studio", "Spotlight"],
    saves: 672,
    category: "Music",
  },
  {
    id: "fp8",
    type: "work_post" as const,
    creator: MOCK_CREATORS[2],
    timestamp: "1d ago",
    title: "Bug Report Log — Indie RPG QA Sprint",
    caption: "Just wrapped a 2-week QA sprint for an indie RPG studio. Found 47 reproducible bugs across 3 platforms. Logging methodology, regression test templates, and priority triage notes available.",
    mediaUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=2670&auto=format&fit=crop",
    tags: ["Game Testing / QA", "Playtesting", "Indie Games"],
    saves: 156,
    category: "Gaming",
    bug_details: {
      title: "Indie RPG Quest State Reset Bug",
      severity: "high" as const,
      platforms: ["PC", "Console"],
      steps: [
        "Load the game save from Chapter 3.",
        "Talk to the Merchant NPC at the crossroads.",
        "Cancel the trade screen immediately.",
        "Check quest log - main quest progress is reset to 0%."
      ],
      stackTrace: "QuestManager.cs:Line 142\nNullReferenceException: Object reference not set to an instance of an object at QuestManager.ResetActiveQuest()",
      screenshotUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=2670&auto=format&fit=crop"
    }
  }
];

export const MOCK_FLARES: Flare[] = [
  {
    id: "f1",
    user_id: "1",
    media_url: "https://assets.mixkit.co/videos/preview/mixkit-abstract-laser-lights-background-loop-41851-large.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2564&auto=format&fit=crop",
    caption: "Nebula OS Shimmer Effect. Tinkering with custom CSS backdrop filters and radial glows for the window headers. Let me know what you think of this animation! ✦",
    tags: ["UI Design", "CSS", "Motion"],
    duration_seconds: 12,
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(), // 2h ago
    spark_count: 42,
    users: {
      display_name: "Aria Chen",
      handle: "aria.creates",
      avatar_url: "https://api.dicebear.com/8.x/lorelei/svg?seed=aria&backgroundColor=6c5ce7"
    }
  },
  {
    id: "f2",
    user_id: "5",
    media_url: "https://assets.mixkit.co/videos/preview/mixkit-tunnel-of-futuristic-blue-neon-lights-42283-large.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=2670&auto=format&fit=crop",
    caption: "Warp Tunnel. Rendered entirely in WebGL with Three.js. Standard GLSL shader running on a customized cylinder geometry. Highly responsive to scroll inputs.",
    tags: ["WebGL", "Three.js", "GLSL"],
    duration_seconds: 15,
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(), // 5h ago
    spark_count: 128,
    users: {
      display_name: "Eli Ramos",
      handle: "eli.motion",
      avatar_url: "https://api.dicebear.com/8.x/lorelei/svg?seed=eli&backgroundColor=a29bfe"
    }
  },
  {
    id: "f3",
    user_id: "3",
    media_url: "https://assets.mixkit.co/videos/preview/mixkit-rotating-cube-with-neon-edges-42277-large.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?q=80&w=2564&auto=format&fit=crop",
    caption: "Hypercube. Playing with neon wireframe reflections in Octane Render. The glass refraction index is key here. What's your go-to render engine for glass?",
    tags: ["3D Art", "Blender", "Octane"],
    duration_seconds: 10,
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(), // 12h ago
    spark_count: 95,
    users: {
      display_name: "Luna Voss",
      handle: "lunavisuals",
      avatar_url: "https://api.dicebear.com/8.x/lorelei/svg?seed=luna&backgroundColor=fd79a8"
    }
  },
  {
    id: "f4",
    user_id: "4",
    media_url: "https://assets.mixkit.co/videos/preview/mixkit-retro-futuristic-grid-background-42284-large.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1678324424699-4c12513fdf1b?q=80&w=2670&auto=format&fit=crop",
    caption: "AI Audio-Reactive Grid. Generating landscapes dynamically using Stable Diffusion ControlNet based on real-time FFT frequency analysis. Super smooth 60fps.",
    tags: ["AI", "Stable Diffusion", "Python"],
    duration_seconds: 20,
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(), // 1d ago
    spark_count: 67,
    users: {
      display_name: "Kira Nakamura",
      handle: "kira.dev",
      avatar_url: "https://api.dicebear.com/8.x/lorelei/svg?seed=kira&backgroundColor=fdcb6e"
    }
  },
  {
    id: "f5",
    user_id: "2",
    media_url: "https://assets.mixkit.co/videos/preview/mixkit-flying-through-a-futuristic-neon-grid-42285-large.mp4",
    thumbnail_url: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=2670&auto=format&fit=crop",
    caption: "Cyber Grid Journey. Developing a procedural canvas shader path with Canvas 2D API for lightweight 2D neon loops. Weighing in at only 12KB gzip.",
    tags: ["Code", "Creative", "Canvas"],
    duration_seconds: 14,
    created_at: new Date(Date.now() - 3600000 * 48).toISOString(), // 2d ago
    spark_count: 88,
    users: {
      display_name: "Zane Okafor",
      handle: "zanecode",
      avatar_url: "https://api.dicebear.com/8.x/lorelei/svg?seed=zane&backgroundColor=00cec9"
    }
  }
];

